name: Build and Publish Docker Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set environment variables
        run: echo "KOLIBRI_RUN_MODE=dev" >> $GITHUB_ENV


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          make docker-build-base
          make docker-devserver-image
          docker tag learningequality/kolibridev ghcr.io/${{ github.repository }}/kolibridev:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/kolibridev:latest
